name: Notifications

on:
  push:
    branches:
      - master

jobs:
  notifications:
    name: Discord Commits
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Discord Commits
      uses: dearimgui/github_discord_notifier@latest
      with:
        discord-webhook: ${{ secrets.DISCORD_WEBHOOK_COMMITS }}
        github-token: ${{ github.token }}
        action-task: discord-commits
        discord-filter: "'{{ github.branch }}' == 'master'"
        discord-username: GitHub
